name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю для правильного определения версии
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'  # Встроенное кэширование Gradle
          
      - name: Check Java version
        run: java -version
          
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
          
      - name: Check Gradle wrapper
        run: ./gradlew --version
          
      - name: Build with Gradle
        run: ./gradlew build --info
        timeout-minutes: 10
        continue-on-error: false

      - name: Publish to GitHub Packages
        if: success()
        run: ./gradlew publish
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }} 